### ISSUE TITLE
STT issue

### ISSUE THREAD

**Issue by NithinP** [NeuralHarbour/LLM-Based-3D-Avatar-Assistant#1]
FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
WebSocket server is running on ws://0.0.0.0:9002
connection handler failed
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\asyncio\server.py", line 373, in conn_handler
    await self.handler(connection)
TypeError: receive_audio_stream() missing 1 required positional argument: 'path'
connection handler failed
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\asyncio\server.py", line 373, in conn_handler
    await self.handler(connection)
TypeError: receive_audio_stream() missing 1 required positional argument: 'path'

**Comment by Ryuzaki9623** [comment]
The bug has now been fixed 

The following changes were made

1. Removed the path parameter from receive_audio_stream()
2. Added FFMPEG check

Also make sure that FFMPEG is installed in the system
